logging:
  file:
    name: logs/application.log
    path: ${user.dir}
  config: classpath:logback-spring.xml
  #config: ${user.dir}/config/logback-spring.xml
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ERROR
    com:
      archivsoft: INFO
    jdbc:
      audit: OFF
      connection: OFF
      resultset: OFF
      resultsettable: OFF
      sqlonly: INFO
      sqltiming: ERROR
    org:
      springframework:
        boot: INFO
#      hibernate:
#        SQL: ERROR
#        type.descriptor.sql: trace
#jdbc setting
spring:
  websocket:
    max-text-message-size: 50MB
    max-binary-message-size: 50MB
    task-execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 1000
  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #    hikari:
#      auto-commit: false
#      connection-test-query: SELECT 1
#      maximum-pool-size: 50
#      minimum-idle: 5
#      connection-timeout: 300000
#    initialize: false
    #    url: jdbc:log4jdbc:mariadb://10.0.0.13:3306/sbms
#    url: jdbc:log4jdbc:mysql://10.10.10.11:3306/sbms?allowPublicKeyRetrieval=true&useSSL=false
#    url: jdbc:mysql://10.10.10.11:3306/sbms?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:p6spy:mysql://10.0.0.13:3306/sbms?allowPublicKeyRetrieval=true&useSSL=false
    username: sbms
    password: Gunpo1212!Q
  main:
    banner-mode: 'off'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  pid:
    file: .pid
  security:
    user:
      algorithm: rms
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  spring:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/


mybatis:
  config-location: classpath:mybatis-config.xml
  #  mapper-locations: file://${user.dir}/ons/config/mapper/**/*.xml
  mapper-locations: classpath:mapper/*.xml

rms:
  default:
    main: /my
app:
  jwt:
    secret_key: mySecretKey12345678901234567890123456789012
server:
  port: 8080
  compression:
    enabled: true
  servlet:
    session:
      timeout: 86400
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
upload:
  path: /data/storage/uploads/