# ?? ???? JDBC ???? (MariaDB)
realdriver=com.mysql.cj.jdbc.Driver

# ?? ?? ??: ?? ???? ????
logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat

# ?? ?? ??: Slf4J (logback-spring.xml? ???)
appender=com.p6spy.engine.spy.appender.Slf4JLogger

# ?? ?? (DEBUG ??)
logLevel=INFO

# SQL ?? ?? (?? ?? ??)
outagedetection=true
outagedetection.interval=2

# ?? ?? ?? (?? ON, ??? OFF? ?? ??)
executionThreshold=0   # 0?? ?? ?? ??

# ?? ?? (??)
dateformat=yyyy-MM-dd HH:mm:ss.SSS

# ?? ???? ?? (??: ? ??? ??? ?? ALL)
# ex: statement, result, connection, commit ?
# ex) categories=statement,commit,result
