realdriver=com.mysql.cj.jdbc.Driver
logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logLevel=WARN
outagedetection=true
outagedetection.interval=2
executionThreshold=0   # 0?? ?? ?? ??
dateformat=yyyy-MM-dd HH:mm:ss.SSS
